// =============================================================================
// MERIDIAN CAPITAL PARTNERS — MOCK DATA STORE
// All data matches realistic_seed.sql exactly
// =============================================================================

export const USERS = [
  { id: 'usr_001', email: 'admin@privara.io',    full_name: 'James Kamau',       role: 'admin'    },
  { id: 'usr_002', email: 'hr@privara.io',        full_name: 'Amina Osei',        role: 'hr'       },
  { id: 'usr_003', email: 'hr.ops@meridian.vc',   full_name: 'Priya Nair',        role: 'hr'       },
  { id: 'usr_004', email: 'finance@privara.io',   full_name: 'Collins Otieno',    role: 'finance'  },
  { id: 'usr_005', email: 'cfo@meridian.vc',      full_name: 'Fatima Al-Hassan',  role: 'finance'  },
  { id: 'usr_006', email: 'auditor@privara.io',   full_name: 'David Mwangi',      role: 'auditor'  },
  { id: 'usr_007', email: 'external.audit@kpmg-ea.com', full_name: 'Grace Achieng', role: 'auditor' },
  { id: 'usr_008', email: 'employee@privara.io',  full_name: 'Evans Mutua',       role: 'employee' },
  { id: 'demo_admin',    email: 'demo.admin@privara.io',    full_name: 'Demo Admin',    role: 'admin'    },
  { id: 'demo_hr',       email: 'demo.hr@privara.io',       full_name: 'Demo HR',       role: 'hr'       },
  { id: 'demo_finance',  email: 'demo.finance@privara.io',  full_name: 'Demo CFO',      role: 'finance'  },
  { id: 'demo_auditor',  email: 'demo.auditor@privara.io',  full_name: 'Demo Auditor',  role: 'auditor'  },
  { id: 'demo_employee', email: 'demo.employee@privara.io', full_name: 'Demo Employee', role: 'employee' },
]

// Passwords: all accounts use "Privara2026!"
export const CREDENTIALS = {
  'admin@privara.io':           { password: 'Privara2026!', user_id: 'usr_001' },
  'hr@privara.io':              { password: 'Privara2026!', user_id: 'usr_002' },
  'hr.ops@meridian.vc':         { password: 'Privara2026!', user_id: 'usr_003' },
  'finance@privara.io':         { password: 'Privara2026!', user_id: 'usr_004' },
  'cfo@meridian.vc':            { password: 'Privara2026!', user_id: 'usr_005' },
  'auditor@privara.io':         { password: 'Privara2026!', user_id: 'usr_006' },
  'external.audit@kpmg-ea.com': { password: 'Privara2026!', user_id: 'usr_007' },
  'employee@privara.io':        { password: 'Privara2026!', user_id: 'usr_008' },
}

export const PAYROLL_BATCHES = [
  {
    id: 'batch_mar_2026',
    name: 'March 2026 — Executive & Senior Staff',
    period_start: '2026-03-01',
    period_end:   '2026-03-31',
    total_records: 14,
    status: 'audited',
    created_by: 'usr_002',
    created_at: '2026-03-28T09:00:00Z',
  },
  {
    id: 'batch_apr_2026',
    name: 'April 2026 — All Staff USD Payroll',
    period_start: '2026-04-01',
    period_end:   '2026-04-30',
    total_records: 18,
    status: 'encrypted',
    created_by: 'usr_002',
    created_at: '2026-04-28T09:15:00Z',
  },
  {
    id: 'batch_apr_kes_2026',
    name: 'April 2026 — Nairobi Office KES Supplement',
    period_start: '2026-04-01',
    period_end:   '2026-04-30',
    total_records: 11,
    status: 'encrypted',
    created_by: 'usr_003',
    created_at: '2026-04-28T10:00:00Z',
  },
  {
    id: 'batch_may_2026',
    name: 'May 2026 — All Staff USD Payroll',
    period_start: '2026-05-01',
    period_end:   '2026-05-31',
    total_records: 19,
    status: 'encrypted',
    created_by: 'usr_002',
    created_at: '2026-05-28T09:00:00Z',
  },
]

// Records keyed by batch_id
export const PAYROLL_RECORDS = {
  batch_mar_2026: [
    { id: 'pr_mar_001', batch_id: 'batch_mar_2026', employee_id: 'EMP-0001', employee_name: 'James Kamau',      department: 'Executive',        gross_salary: 18500, deductions: 2775, net_salary: 15725, currency: 'USD' },
    { id: 'pr_mar_002', batch_id: 'batch_mar_2026', employee_id: 'EMP-0002', employee_name: 'Fatima Al-Hassan', department: 'Finance',          gross_salary: 16200, deductions: 2430, net_salary: 13770, currency: 'USD' },
    { id: 'pr_mar_003', batch_id: 'batch_mar_2026', employee_id: 'EMP-0003', employee_name: 'Amina Osei',       department: 'Human Resources',  gross_salary:  9800, deductions: 1470, net_salary:  8330, currency: 'USD' },
    { id: 'pr_mar_004', batch_id: 'batch_mar_2026', employee_id: 'EMP-0004', employee_name: 'Collins Otieno',   department: 'Finance',          gross_salary: 12400, deductions: 1860, net_salary: 10540, currency: 'USD' },
    { id: 'pr_mar_005', batch_id: 'batch_mar_2026', employee_id: 'EMP-0005', employee_name: 'Dr. Kwame Asante', department: 'Investment',       gross_salary: 21000, deductions: 3150, net_salary: 17850, currency: 'USD' },
    { id: 'pr_mar_006', batch_id: 'batch_mar_2026', employee_id: 'EMP-0006', employee_name: 'Ngozi Adeyemi',    department: 'Investment',       gross_salary: 19500, deductions: 2925, net_salary: 16575, currency: 'USD' },
    { id: 'pr_mar_007', batch_id: 'batch_mar_2026', employee_id: 'EMP-0007', employee_name: 'Tariq Rahman',     department: 'Technology',       gross_salary: 14800, deductions: 2220, net_salary: 12580, currency: 'USD' },
    { id: 'pr_mar_008', batch_id: 'batch_mar_2026', employee_id: 'EMP-0008', employee_name: 'Aisha Diallo',     department: 'Legal',            gross_salary: 17300, deductions: 2595, net_salary: 14705, currency: 'USD' },
    { id: 'pr_mar_009', batch_id: 'batch_mar_2026', employee_id: 'EMP-0009', employee_name: 'Brian Kariuki',    department: 'Operations',       gross_salary:  8900, deductions: 1335, net_salary:  7565, currency: 'USD' },
    { id: 'pr_mar_010', batch_id: 'batch_mar_2026', employee_id: 'EMP-0010', employee_name: 'Sarah Njoroge',    department: 'Communications',   gross_salary:  9200, deductions: 1380, net_salary:  7820, currency: 'USD' },
    { id: 'pr_mar_011', batch_id: 'batch_mar_2026', employee_id: 'EMP-0011', employee_name: 'Emeka Okonkwo',   department: 'Investment',       gross_salary: 15600, deductions: 2340, net_salary: 13260, currency: 'USD' },
    { id: 'pr_mar_012', batch_id: 'batch_mar_2026', employee_id: 'EMP-0012', employee_name: 'Priya Nair',       department: 'Human Resources',  gross_salary:  9100, deductions: 1365, net_salary:  7735, currency: 'USD' },
    { id: 'pr_mar_013', batch_id: 'batch_mar_2026', employee_id: 'EMP-0013', employee_name: 'Marcus Webb',      department: 'Research',         gross_salary: 13200, deductions: 1980, net_salary: 11220, currency: 'USD' },
    { id: 'pr_mar_014', batch_id: 'batch_mar_2026', employee_id: 'EMP-0014', employee_name: 'Zara Al-Qasim',   department: 'Compliance',       gross_salary: 11800, deductions: 1770, net_salary: 10030, currency: 'USD' },
  ],
  batch_apr_2026: [
    { id: 'pr_apr_001', batch_id: 'batch_apr_2026', employee_id: 'EMP-0001', employee_name: 'James Kamau',      department: 'Executive',        gross_salary: 18500, deductions: 2775, net_salary: 15725, currency: 'USD' },
    { id: 'pr_apr_002', batch_id: 'batch_apr_2026', employee_id: 'EMP-0002', employee_name: 'Fatima Al-Hassan', department: 'Finance',          gross_salary: 16200, deductions: 2430, net_salary: 13770, currency: 'USD' },
    { id: 'pr_apr_003', batch_id: 'batch_apr_2026', employee_id: 'EMP-0003', employee_name: 'Amina Osei',       department: 'Human Resources',  gross_salary:  9800, deductions: 1470, net_salary:  8330, currency: 'USD' },
    { id: 'pr_apr_004', batch_id: 'batch_apr_2026', employee_id: 'EMP-0004', employee_name: 'Collins Otieno',   department: 'Finance',          gross_salary: 12400, deductions: 1860, net_salary: 10540, currency: 'USD' },
    { id: 'pr_apr_005', batch_id: 'batch_apr_2026', employee_id: 'EMP-0005', employee_name: 'Dr. Kwame Asante', department: 'Investment',       gross_salary: 21000, deductions: 3150, net_salary: 17850, currency: 'USD' },
    { id: 'pr_apr_006', batch_id: 'batch_apr_2026', employee_id: 'EMP-0006', employee_name: 'Ngozi Adeyemi',    department: 'Investment',       gross_salary: 19500, deductions: 2925, net_salary: 16575, currency: 'USD' },
    { id: 'pr_apr_007', batch_id: 'batch_apr_2026', employee_id: 'EMP-0007', employee_name: 'Tariq Rahman',     department: 'Technology',       gross_salary: 15200, deductions: 2280, net_salary: 12920, currency: 'USD' },
    { id: 'pr_apr_008', batch_id: 'batch_apr_2026', employee_id: 'EMP-0008', employee_name: 'Aisha Diallo',     department: 'Legal',            gross_salary: 17300, deductions: 2595, net_salary: 14705, currency: 'USD' },
    { id: 'pr_apr_009', batch_id: 'batch_apr_2026', employee_id: 'EMP-0009', employee_name: 'Brian Kariuki',    department: 'Operations',       gross_salary:  8900, deductions: 1335, net_salary:  7565, currency: 'USD' },
    { id: 'pr_apr_010', batch_id: 'batch_apr_2026', employee_id: 'EMP-0010', employee_name: 'Sarah Njoroge',    department: 'Communications',   gross_salary:  9200, deductions: 1380, net_salary:  7820, currency: 'USD' },
    { id: 'pr_apr_011', batch_id: 'batch_apr_2026', employee_id: 'EMP-0011', employee_name: 'Emeka Okonkwo',   department: 'Investment',       gross_salary: 15600, deductions: 2340, net_salary: 13260, currency: 'USD' },
    { id: 'pr_apr_012', batch_id: 'batch_apr_2026', employee_id: 'EMP-0012', employee_name: 'Priya Nair',       department: 'Human Resources',  gross_salary:  9100, deductions: 1365, net_salary:  7735, currency: 'USD' },
    { id: 'pr_apr_013', batch_id: 'batch_apr_2026', employee_id: 'EMP-0013', employee_name: 'Marcus Webb',      department: 'Research',         gross_salary: 13200, deductions: 1980, net_salary: 11220, currency: 'USD' },
    { id: 'pr_apr_014', batch_id: 'batch_apr_2026', employee_id: 'EMP-0014', employee_name: 'Zara Al-Qasim',   department: 'Compliance',       gross_salary: 11800, deductions: 1770, net_salary: 10030, currency: 'USD' },
    { id: 'pr_apr_015', batch_id: 'batch_apr_2026', employee_id: 'EMP-0015', employee_name: 'Lena Fischer',     department: 'Research',         gross_salary: 12900, deductions: 1935, net_salary: 10965, currency: 'USD' },
    { id: 'pr_apr_016', batch_id: 'batch_apr_2026', employee_id: 'EMP-0016', employee_name: 'Kofi Mensah',      department: 'Investment',       gross_salary: 16800, deductions: 2520, net_salary: 14280, currency: 'USD' },
    { id: 'pr_apr_017', batch_id: 'batch_apr_2026', employee_id: 'EMP-0017', employee_name: 'Yuki Tanaka',      department: 'Technology',       gross_salary: 14100, deductions: 2115, net_salary: 11985, currency: 'USD' },
    { id: 'pr_apr_018', batch_id: 'batch_apr_2026', employee_id: 'EMP-0018', employee_name: 'Chioma Eze',       department: 'Legal',            gross_salary: 13500, deductions: 2025, net_salary: 11475, currency: 'USD' },
  ],
  batch_apr_kes_2026: [
    { id: 'pr_kes_001', batch_id: 'batch_apr_kes_2026', employee_id: 'EMP-0009', employee_name: 'Brian Kariuki',  department: 'Operations',    gross_salary: 145000, deductions: 21750, net_salary: 123250, currency: 'KES' },
    { id: 'pr_kes_002', batch_id: 'batch_apr_kes_2026', employee_id: 'EMP-0010', employee_name: 'Sarah Njoroge',  department: 'Communications',gross_salary: 138000, deductions: 20700, net_salary: 117300, currency: 'KES' },
    { id: 'pr_kes_003', batch_id: 'batch_apr_kes_2026', employee_id: 'EMP-0012', employee_name: 'Priya Nair',     department: 'Human Resources',gross_salary:125000, deductions: 18750, net_salary: 106250, currency: 'KES' },
    { id: 'pr_kes_004', batch_id: 'batch_apr_kes_2026', employee_id: 'EMP-0019', employee_name: 'Samuel Kimani',  department: 'Operations',    gross_salary:  98000, deductions: 14700, net_salary:  83300, currency: 'KES' },
    { id: 'pr_kes_005', batch_id: 'batch_apr_kes_2026', employee_id: 'EMP-0020', employee_name: 'Rose Wanjiku',   department: 'Administration',gross_salary:  85000, deductions: 12750, net_salary:  72250, currency: 'KES' },
    { id: 'pr_kes_006', batch_id: 'batch_apr_kes_2026', employee_id: 'EMP-0021', employee_name: 'Peter Odhiambo', department: 'Security',      gross_salary:  72000, deductions: 10800, net_salary:  61200, currency: 'KES' },
    { id: 'pr_kes_007', batch_id: 'batch_apr_kes_2026', employee_id: 'EMP-0022', employee_name: 'Mary Auma',      department: 'Administration',gross_salary:  78000, deductions: 11700, net_salary:  66300, currency: 'KES' },
    { id: 'pr_kes_008', batch_id: 'batch_apr_kes_2026', employee_id: 'EMP-0023', employee_name: 'John Otieno',    department: 'Facilities',    gross_salary:  68000, deductions: 10200, net_salary:  57800, currency: 'KES' },
    { id: 'pr_kes_009', batch_id: 'batch_apr_kes_2026', employee_id: 'EMP-0024', employee_name: 'Alice Muthoni',  department: 'IT Support',    gross_salary: 112000, deductions: 16800, net_salary:  95200, currency: 'KES' },
    { id: 'pr_kes_010', batch_id: 'batch_apr_kes_2026', employee_id: 'EMP-0025', employee_name: 'Dennis Kiprop',  department: 'Accounting',    gross_salary: 105000, deductions: 15750, net_salary:  89250, currency: 'KES' },
    { id: 'pr_kes_011', batch_id: 'batch_apr_kes_2026', employee_id: 'EMP-0026', employee_name: 'Winnie Chebet',  department: 'Legal Aid',     gross_salary: 118000, deductions: 17700, net_salary: 100300, currency: 'KES' },
  ],
  batch_may_2026: [
    { id: 'pr_may_001', batch_id: 'batch_may_2026', employee_id: 'EMP-0001', employee_name: 'James Kamau',      department: 'Executive',       gross_salary: 18500, deductions: 2775, net_salary: 15725, currency: 'USD' },
    { id: 'pr_may_002', batch_id: 'batch_may_2026', employee_id: 'EMP-0002', employee_name: 'Fatima Al-Hassan', department: 'Finance',         gross_salary: 16200, deductions: 2430, net_salary: 13770, currency: 'USD' },
    { id: 'pr_may_003', batch_id: 'batch_may_2026', employee_id: 'EMP-0003', employee_name: 'Amina Osei',       department: 'Human Resources', gross_salary:  9800, deductions: 1470, net_salary:  8330, currency: 'USD' },
    { id: 'pr_may_004', batch_id: 'batch_may_2026', employee_id: 'EMP-0004', employee_name: 'Collins Otieno',   department: 'Finance',         gross_salary: 12400, deductions: 1860, net_salary: 10540, currency: 'USD' },
    { id: 'pr_may_005', batch_id: 'batch_may_2026', employee_id: 'EMP-0005', employee_name: 'Dr. Kwame Asante', department: 'Investment',      gross_salary: 21000, deductions: 3150, net_salary: 17850, currency: 'USD' },
    { id: 'pr_may_006', batch_id: 'batch_may_2026', employee_id: 'EMP-0006', employee_name: 'Ngozi Adeyemi',    department: 'Investment',      gross_salary: 20200, deductions: 3030, net_salary: 17170, currency: 'USD' },
    { id: 'pr_may_007', batch_id: 'batch_may_2026', employee_id: 'EMP-0007', employee_name: 'Tariq Rahman',     department: 'Technology',      gross_salary: 15200, deductions: 2280, net_salary: 12920, currency: 'USD' },
    { id: 'pr_may_008', batch_id: 'batch_may_2026', employee_id: 'EMP-0008', employee_name: 'Aisha Diallo',     department: 'Legal',           gross_salary: 17300, deductions: 2595, net_salary: 14705, currency: 'USD' },
    { id: 'pr_may_009', batch_id: 'batch_may_2026', employee_id: 'EMP-0009', employee_name: 'Brian Kariuki',    department: 'Operations',      gross_salary:  9200, deductions: 1380, net_salary:  7820, currency: 'USD' },
    { id: 'pr_may_010', batch_id: 'batch_may_2026', employee_id: 'EMP-0010', employee_name: 'Sarah Njoroge',    department: 'Communications',  gross_salary:  9500, deductions: 1425, net_salary:  8075, currency: 'USD' },
    { id: 'pr_may_011', batch_id: 'batch_may_2026', employee_id: 'EMP-0011', employee_name: 'Emeka Okonkwo',   department: 'Investment',      gross_salary: 15600, deductions: 2340, net_salary: 13260, currency: 'USD' },
    { id: 'pr_may_012', batch_id: 'batch_may_2026', employee_id: 'EMP-0012', employee_name: 'Priya Nair',       department: 'Human Resources', gross_salary:  9100, deductions: 1365, net_salary:  7735, currency: 'USD' },
    { id: 'pr_may_013', batch_id: 'batch_may_2026', employee_id: 'EMP-0013', employee_name: 'Marcus Webb',      department: 'Research',        gross_salary: 13200, deductions: 1980, net_salary: 11220, currency: 'USD' },
    { id: 'pr_may_014', batch_id: 'batch_may_2026', employee_id: 'EMP-0014', employee_name: 'Zara Al-Qasim',   department: 'Compliance',      gross_salary: 11800, deductions: 1770, net_salary: 10030, currency: 'USD' },
    { id: 'pr_may_015', batch_id: 'batch_may_2026', employee_id: 'EMP-0015', employee_name: 'Lena Fischer',     department: 'Research',        gross_salary: 12900, deductions: 1935, net_salary: 10965, currency: 'USD' },
    { id: 'pr_may_016', batch_id: 'batch_may_2026', employee_id: 'EMP-0016', employee_name: 'Kofi Mensah',      department: 'Investment',      gross_salary: 16800, deductions: 2520, net_salary: 14280, currency: 'USD' },
    { id: 'pr_may_017', batch_id: 'batch_may_2026', employee_id: 'EMP-0017', employee_name: 'Yuki Tanaka',      department: 'Technology',      gross_salary: 14100, deductions: 2115, net_salary: 11985, currency: 'USD' },
    { id: 'pr_may_018', batch_id: 'batch_may_2026', employee_id: 'EMP-0018', employee_name: 'Chioma Eze',       department: 'Legal',           gross_salary: 13500, deductions: 2025, net_salary: 11475, currency: 'USD' },
    { id: 'pr_may_019', batch_id: 'batch_may_2026', employee_id: 'EMP-0019', employee_name: 'Samuel Kimani',    department: 'Operations',      gross_salary:  8600, deductions: 1290, net_salary:  7310, currency: 'USD' },
  ],
}

export const TREASURY_REQUESTS = [
  { id: 'treq_001', title: 'Q1 2026 Office Infrastructure Upgrade',          amount: 145000, currency: 'USD', purpose: 'Server rack expansion, UPS systems, and network redundancy for Nairobi HQ. Required for ISO 27001 compliance audit scheduled May 2026.',                                                                                                                   risk_level: 'low',    status: 'executed', required_approvals: 2, current_approvals: 2, requested_by: 'usr_004', created_at: '2026-03-05T10:00:00Z', updated_at: '2026-03-08T14:30:00Z' },
  { id: 'treq_002', title: 'Lagos Office Lease — Q2 2026',                   amount:  87500, currency: 'USD', purpose: 'Six-month lease extension for Victoria Island office. Portfolio company board meetings and LP relations events.',                                                                                                                                         risk_level: 'low',    status: 'executed', required_approvals: 2, current_approvals: 2, requested_by: 'usr_005', created_at: '2026-03-12T09:00:00Z', updated_at: '2026-03-14T11:00:00Z' },
  { id: 'treq_003', title: 'Investment Research Platform Subscription',       amount:  42000, currency: 'USD', purpose: 'Annual Bloomberg Terminal renewal (3 seats) + PitchBook Data license for deal sourcing. Essential for Q2 portfolio review.',                                                                                                                             risk_level: 'low',    status: 'executed', required_approvals: 2, current_approvals: 2, requested_by: 'usr_004', created_at: '2026-03-20T14:00:00Z', updated_at: '2026-03-21T09:30:00Z' },
  { id: 'treq_004', title: 'Pan-Africa LP Summit — Event Sponsorship',        amount:  95000, currency: 'USD', purpose: 'Headline sponsorship of the Africa Private Capital Association summit in Kigali, June 2026. 400+ LPs attending. Direct pipeline opportunity for Fund III close.',                                                                                         risk_level: 'medium', status: 'approved', required_approvals: 2, current_approvals: 2, requested_by: 'usr_005', created_at: '2026-04-10T11:00:00Z', updated_at: '2026-04-15T16:00:00Z' },
  { id: 'treq_005', title: 'ESG Compliance Software — 3-Year Contract',       amount:  68000, currency: 'USD', purpose: 'Novata ESG data management platform. Required for ILPA reporting standards compliance. LPs requesting ESG metrics from Q3 2026.',                                                                                                                        risk_level: 'low',    status: 'approved', required_approvals: 2, current_approvals: 2, requested_by: 'usr_004', created_at: '2026-04-22T10:30:00Z', updated_at: '2026-04-25T14:00:00Z' },
  { id: 'treq_006', title: 'Q3 2026 Digital Marketing & Brand Campaign',      amount: 120000, currency: 'USD', purpose: 'Integrated digital campaign targeting family offices and institutional LPs in Europe and the Gulf. Includes LinkedIn sponsored content, thought leadership series, and Campden Wealth magazine placement. Supports Fund III fundraising narrative.',         risk_level: 'medium', status: 'pending',  required_approvals: 2, current_approvals: 1, requested_by: 'usr_005', created_at: '2026-05-20T09:00:00Z', updated_at: '2026-05-20T09:00:00Z' },
  { id: 'treq_007', title: 'Nairobi Talent Acquisition — 4 Senior Hires',    amount:  55000, currency: 'USD', purpose: 'Executive search retainer fees for VP Investment (x2), Head of Risk, and Senior Legal Counsel. Using Korn Ferry East Africa. Positions critical for Fund III deployment capacity.',                                                                      risk_level: 'low',    status: 'pending',  required_approvals: 2, current_approvals: 0, requested_by: 'usr_004', created_at: '2026-05-22T14:00:00Z', updated_at: '2026-05-22T14:00:00Z' },
  { id: 'treq_008', title: 'Cybersecurity Audit & Penetration Testing',       amount:  38500, currency: 'USD', purpose: 'Annual third-party security audit by Sievert Larsen Consulting. Scope: cloud infrastructure, Privara Lite deployment, investor portal. Required for SOC 2 Type II certification renewal.',                                                              risk_level: 'low',    status: 'pending',  required_approvals: 2, current_approvals: 0, requested_by: 'usr_005', created_at: '2026-05-24T10:00:00Z', updated_at: '2026-05-24T10:00:00Z' },
  { id: 'treq_009', title: 'Strategic Reserve — Distressed Asset Opportunity',amount: 500000, currency: 'USD', purpose: 'Co-investment reserve allocation for identified distressed asset in the logistics sector (Project Baobab). IRR model shows 28% projected return. 72-hour exclusivity window requires rapid capital deployment decision.',                                   risk_level: 'high',   status: 'pending',  required_approvals: 3, current_approvals: 1, requested_by: 'usr_005', created_at: '2026-05-25T16:00:00Z', updated_at: '2026-05-25T16:00:00Z' },
  { id: 'treq_010', title: 'Luxury Corporate Retreat — Seychelles',           amount:  78000, currency: 'USD', purpose: 'Annual team retreat and strategy offsite. Proposed venue: Four Seasons Desroches Island, Seychelles. 5 nights, 22 attendees.',                                                                                                                          risk_level: 'medium', status: 'rejected', required_approvals: 2, current_approvals: 0, requested_by: 'usr_004', created_at: '2026-04-08T11:00:00Z', updated_at: '2026-04-09T09:00:00Z' },
]

export const PROPOSALS = [
  {
    id: 'prop_001',
    title: 'Approve Fund III Target Size Increase to $350M',
    description: 'The Investment Committee proposes increasing the Fund III hard cap from $250M to $350M following stronger-than-anticipated LP demand. Current commitments stand at $198M with 14 weeks remaining in the fundraising period. Increasing the cap allows us to accommodate 4 additional anchor LP commitments totalling $95M currently on soft-circle.',
    status: 'passed', created_by: 'usr_001',
    voting_ends_at: '2026-03-20T18:00:00Z',
    created_at:     '2026-03-13T10:00:00Z',
  },
  {
    id: 'prop_002',
    title: 'Ratify ESG Investment Policy — SFDR Article 8 Alignment',
    description: 'Proposal to formally adopt the revised ESG Investment Policy aligning Meridian Capital with SFDR Article 8 classification. This enables marketing to European institutional investors restricted to Article 8+ funds. Policy requires minimum 40% portfolio companies to have documented ESG improvement plans within 24 months of investment.',
    status: 'passed', created_by: 'usr_001',
    voting_ends_at: '2026-04-05T18:00:00Z',
    created_at:     '2026-03-28T14:00:00Z',
  },
  {
    id: 'prop_003',
    title: 'Approve Co-Investment Program for Fund III LPs',
    description: 'Establish a formal co-investment program allowing Fund III LPs to participate in deal-by-deal investments above $15M with a 30-day right of first refusal. Co-investments carry no management fee and 5% carried interest (vs 20% in the main fund). Program designed to increase LP stickiness for Fund IV.',
    status: 'passed', created_by: 'usr_001',
    voting_ends_at: '2026-04-25T18:00:00Z',
    created_at:     '2026-04-18T09:00:00Z',
  },
  {
    id: 'prop_004',
    title: 'Expand Treasury Ceiling to $500K Operating Reserve',
    description: 'Finance team proposes expanding the quarterly operating treasury from $250K to $500K to accommodate accelerated hiring (4 senior roles), increased deal flow activity, and the APCA summit sponsorship. Reserve will remain in money-market instruments when not deployed. Any draw above $150K requires 3-party CFO + CEO + Board approval.',
    status: 'active', created_by: 'usr_001',
    voting_ends_at: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    created_at:     '2026-05-20T10:00:00Z',
  },
  {
    id: 'prop_005',
    title: 'Mandate Privara Lite as Official Financial Operations Platform',
    description: 'Following 3-month pilot, the Operations Committee proposes formally adopting Privara Lite as the mandatory system for all payroll processing, treasury approvals above $10K, and board-level governance votes. Replaces current spreadsheet-based payroll and email-based treasury approvals. Estimated time savings: 12 hours/month across finance and HR teams.',
    status: 'active', created_by: 'usr_001',
    voting_ends_at: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
    created_at:     '2026-05-22T14:00:00Z',
  },
]

export const VOTE_TALLIES = {
  prop_001: { yes_count: 9, no_count: 1, abstain_count: 1, total_votes: 11, outcome: 'passed'   },
  prop_002: { yes_count: 10, no_count: 0, abstain_count: 1, total_votes: 11, outcome: 'passed'  },
  prop_003: { yes_count: 8,  no_count: 2, abstain_count: 0, total_votes: 10, outcome: 'passed'  },
  prop_004: { yes_count: 4,  no_count: 1, abstain_count: 0, total_votes: 5,  outcome: 'pending' },
  prop_005: { yes_count: 3,  no_count: 0, abstain_count: 0, total_votes: 3,  outcome: 'pending' },
}

export const AUDIT_REQUESTS = [
  { id: 'areq_001', auditor_id: 'usr_006', auditor_name: 'David Mwangi',   resource_type: 'payroll',  resource_id: 'batch_mar_2026', reason: 'Q1 2026 payroll compliance verification for KRA PAYE audit scheduled March 31. Requires salary verification for 14 executive and senior staff members.',                                   status: 'granted', created_at: '2026-03-25T10:00:00Z' },
  { id: 'areq_002', auditor_id: 'usr_007', auditor_name: 'Grace Achieng',  resource_type: 'treasury', resource_id: 'treq_001',       reason: 'KPMG East Africa annual audit engagement. Verifying Q1 capital expenditure classification and vendor payment authorisation trail for infrastructure upgrade.',                               status: 'granted', created_at: '2026-04-15T11:00:00Z' },
  { id: 'areq_003', auditor_id: 'usr_006', auditor_name: 'David Mwangi',   resource_type: 'treasury', resource_id: 'treq_009',       reason: 'Risk committee review of Project Baobab co-investment opportunity. Verifying treasury reserve adequacy and approval threshold compliance for $500K deployment.',                          status: 'pending', created_at: '2026-05-25T18:00:00Z' },
  { id: 'areq_004', auditor_id: 'usr_007', auditor_name: 'Grace Achieng',  resource_type: 'payroll',  resource_id: 'batch_apr_2026', reason: 'Mid-year payroll compliance spot check. Verifying deduction calculations align with NHIF and NSSF regulatory schedules effective March 2026.',                                            status: 'pending', created_at: '2026-05-26T09:00:00Z' },
]

export const AUDIT_LOGS = [
  { id: 'log_001', actor_id: 'usr_001', actor_role: 'admin',   action: 'system_initialized',        resource_type: 'system',    resource_id: 'privara-lite',   metadata: '{"version":"1.0.0","org":"Meridian Capital Partners"}',                                    occurred_at: '2026-02-01T08:00:00Z' },
  { id: 'log_002', actor_id: 'usr_001', actor_role: 'admin',   action: 'user_created',               resource_type: 'user',      resource_id: 'usr_002',        metadata: '{"role":"hr","email":"hr@privara.io"}',                                                      occurred_at: '2026-02-01T08:15:00Z' },
  { id: 'log_003', actor_id: 'usr_001', actor_role: 'admin',   action: 'user_created',               resource_type: 'user',      resource_id: 'usr_004',        metadata: '{"role":"finance","email":"finance@privara.io"}',                                            occurred_at: '2026-02-01T08:30:00Z' },
  { id: 'log_004', actor_id: 'usr_001', actor_role: 'admin',   action: 'user_created',               resource_type: 'user',      resource_id: 'usr_005',        metadata: '{"role":"finance","email":"cfo@meridian.vc"}',                                              occurred_at: '2026-02-01T09:00:00Z' },
  { id: 'log_005', actor_id: 'usr_001', actor_role: 'admin',   action: 'user_created',               resource_type: 'user',      resource_id: 'usr_006',        metadata: '{"role":"auditor","email":"auditor@privara.io"}',                                            occurred_at: '2026-02-05T10:00:00Z' },
  { id: 'log_006', actor_id: 'usr_002', actor_role: 'hr',      action: 'payroll_batch_uploaded',     resource_type: 'payroll',   resource_id: 'batch_mar_2026', metadata: '{"records":14,"period":"March 2026","encryption":"AES-256-GCM"}',                           occurred_at: '2026-03-28T09:00:00Z' },
  { id: 'log_007', actor_id: 'usr_002', actor_role: 'hr',      action: 'payroll_encrypted',          resource_type: 'payroll',   resource_id: 'batch_mar_2026', metadata: '{"algorithm":"AES-256-GCM","key_id":"key_2026_q1","records_encrypted":14}',                 occurred_at: '2026-03-28T09:01:22Z' },
  { id: 'log_008', actor_id: 'usr_004', actor_role: 'finance', action: 'payroll_decrypted',          resource_type: 'payroll',   resource_id: 'batch_mar_2026', metadata: '{"reason":"CFO salary verification","records_accessed":14}',                                 occurred_at: '2026-03-28T10:30:00Z' },
  { id: 'log_009', actor_id: 'usr_006', actor_role: 'auditor', action: 'audit_access_requested',     resource_type: 'audit',     resource_id: 'areq_001',       metadata: '{"resource":"batch_mar_2026","reason":"KRA PAYE audit"}',                                   occurred_at: '2026-03-25T10:00:00Z' },
  { id: 'log_010', actor_id: 'usr_001', actor_role: 'admin',   action: 'audit_access_granted',       resource_type: 'audit',     resource_id: 'areq_001',       metadata: '{"granted_to":"usr_006","resource":"batch_mar_2026"}',                                      occurred_at: '2026-03-25T14:00:00Z' },
  { id: 'log_011', actor_id: 'usr_006', actor_role: 'auditor', action: 'audit_export_downloaded',    resource_type: 'payroll',   resource_id: 'batch_mar_2026', metadata: '{"file":"audit-batch_mar_2026.csv","records":14}',                                           occurred_at: '2026-03-26T09:00:00Z' },
  { id: 'log_012', actor_id: 'usr_004', actor_role: 'finance', action: 'treasury_request_created',   resource_type: 'treasury',  resource_id: 'treq_001',       metadata: '{"title":"Q1 Infrastructure","amount":145000,"currency":"USD"}',                           occurred_at: '2026-03-05T10:00:00Z' },
  { id: 'log_013', actor_id: 'usr_004', actor_role: 'finance', action: 'treasury_approved',          resource_type: 'treasury',  resource_id: 'treq_001',       metadata: '{"approver":"Collins Otieno","note":"Budget confirmed"}',                                   occurred_at: '2026-03-07T10:00:00Z' },
  { id: 'log_014', actor_id: 'usr_001', actor_role: 'admin',   action: 'treasury_approved',          resource_type: 'treasury',  resource_id: 'treq_001',       metadata: '{"approver":"James Kamau","note":"Approved. Essential for compliance."}',                  occurred_at: '2026-03-08T14:30:00Z' },
  { id: 'log_015', actor_id: 'usr_004', actor_role: 'finance', action: 'treasury_executed_onchain',  resource_type: 'treasury',  resource_id: 'treq_001',       metadata: '{"tx_hash":"0x4f8a2b1c9d3e7f0a","network":"SoDEX Testnet","amount":145000}',               occurred_at: '2026-03-09T10:00:00Z' },
  { id: 'log_016', actor_id: 'usr_005', actor_role: 'finance', action: 'treasury_request_created',   resource_type: 'treasury',  resource_id: 'treq_002',       metadata: '{"title":"Lagos Office Lease","amount":87500,"currency":"USD"}',                          occurred_at: '2026-03-12T09:00:00Z' },
  { id: 'log_017', actor_id: 'usr_001', actor_role: 'admin',   action: 'treasury_request_rejected',  resource_type: 'treasury',  resource_id: 'treq_010',       metadata: '{"title":"Luxury Retreat","reason":"Not appropriate use of capital"}',                    occurred_at: '2026-04-09T09:00:00Z' },
  { id: 'log_018', actor_id: 'usr_001', actor_role: 'admin',   action: 'proposal_created',           resource_type: 'governance',resource_id: 'prop_001',       metadata: '{"title":"Fund III Size Increase","voting_ends":"2026-03-20"}',                           occurred_at: '2026-03-13T10:00:00Z' },
  { id: 'log_019', actor_id: 'usr_001', actor_role: 'admin',   action: 'proposal_tallied',           resource_type: 'governance',resource_id: 'prop_001',       metadata: '{"yes":9,"no":1,"abstain":1,"outcome":"passed"}',                                          occurred_at: '2026-03-20T18:01:00Z' },
  { id: 'log_020', actor_id: 'usr_002', actor_role: 'hr',      action: 'payroll_batch_uploaded',     resource_type: 'payroll',   resource_id: 'batch_apr_2026', metadata: '{"records":18,"period":"April 2026 USD","encryption":"AES-256-GCM"}',                      occurred_at: '2026-04-28T09:15:00Z' },
  { id: 'log_021', actor_id: 'usr_003', actor_role: 'hr',      action: 'payroll_batch_uploaded',     resource_type: 'payroll',   resource_id: 'batch_apr_kes_2026', metadata: '{"records":11,"period":"April 2026 KES","encryption":"AES-256-GCM"}',                  occurred_at: '2026-04-28T10:00:00Z' },
  { id: 'log_022', actor_id: 'usr_005', actor_role: 'finance', action: 'payroll_decrypted',          resource_type: 'payroll',   resource_id: 'batch_apr_2026', metadata: '{"reason":"April payroll CFO sign-off","records_accessed":18}',                             occurred_at: '2026-04-29T09:00:00Z' },
  { id: 'log_023', actor_id: 'usr_007', actor_role: 'auditor', action: 'audit_access_requested',     resource_type: 'audit',     resource_id: 'areq_002',       metadata: '{"resource":"treq_001","engagement":"KPMG Annual Audit 2026"}',                            occurred_at: '2026-04-15T11:00:00Z' },
  { id: 'log_024', actor_id: 'usr_001', actor_role: 'admin',   action: 'audit_access_granted',       resource_type: 'audit',     resource_id: 'areq_002',       metadata: '{"granted_to":"usr_007","scope":"capex_verification"}',                                    occurred_at: '2026-04-15T14:30:00Z' },
  { id: 'log_025', actor_id: 'usr_007', actor_role: 'auditor', action: 'audit_pdf_downloaded',       resource_type: 'treasury',  resource_id: 'treq_001',       metadata: '{"file":"privara-audit-treasury-treq_001.pdf","pages":3}',                                occurred_at: '2026-04-16T10:00:00Z' },
  { id: 'log_026', actor_id: 'usr_002', actor_role: 'hr',      action: 'payroll_batch_uploaded',     resource_type: 'payroll',   resource_id: 'batch_may_2026', metadata: '{"records":19,"period":"May 2026","encryption":"AES-256-GCM"}',                            occurred_at: '2026-05-28T09:00:00Z' },
  { id: 'log_027', actor_id: 'usr_005', actor_role: 'finance', action: 'treasury_request_created',   resource_type: 'treasury',  resource_id: 'treq_006',       metadata: '{"title":"Q3 Digital Marketing","amount":120000,"currency":"USD"}',                       occurred_at: '2026-05-20T09:00:00Z' },
  { id: 'log_028', actor_id: 'usr_005', actor_role: 'finance', action: 'treasury_approved',          resource_type: 'treasury',  resource_id: 'treq_006',       metadata: '{"approver":"Fatima Al-Hassan","note":"LP targeting aligns with Fund III"}',              occurred_at: '2026-05-21T11:00:00Z' },
  { id: 'log_029', actor_id: 'usr_005', actor_role: 'finance', action: 'treasury_request_created',   resource_type: 'treasury',  resource_id: 'treq_009',       metadata: '{"title":"Project Baobab","amount":500000,"currency":"USD"}',                            occurred_at: '2026-05-25T16:00:00Z' },
  { id: 'log_030', actor_id: 'usr_006', actor_role: 'auditor', action: 'audit_access_requested',     resource_type: 'audit',     resource_id: 'areq_003',       metadata: '{"resource":"treq_009","reason":"Risk committee — Project Baobab"}',                      occurred_at: '2026-05-25T18:00:00Z' },
  { id: 'log_031', actor_id: 'usr_001', actor_role: 'admin',   action: 'proposal_created',           resource_type: 'governance',resource_id: 'prop_004',       metadata: '{"title":"Treasury Ceiling Expansion","amount":500000}',                                  occurred_at: '2026-05-20T10:00:00Z' },
  { id: 'log_032', actor_id: 'usr_001', actor_role: 'admin',   action: 'proposal_created',           resource_type: 'governance',resource_id: 'prop_005',       metadata: '{"title":"Privara Lite Platform Mandate"}',                                               occurred_at: '2026-05-22T14:00:00Z' },
  { id: 'log_033', actor_id: 'usr_004', actor_role: 'finance', action: 'payroll_decrypted',          resource_type: 'payroll',   resource_id: 'batch_may_2026', metadata: '{"reason":"May payroll CFO pre-approval check","records_accessed":19}',                   occurred_at: '2026-05-28T10:30:00Z' },
]

export const MARKET_INTELLIGENCE = {
  btc_etf_daily_inflow_usd:  342_800_000,
  btc_etf_total_assets_usd:  58_400_000_000,
  btc_etf_daily_volume_usd:  2_140_000_000,
  btc_etf_cum_inflow_usd:    39_200_000_000,
  btc_price_usd:             98_450,
  btc_24h_change_pct:        2.34,
  inflow_signal:             'INFLOW',
  top_news_tags:             ['ETF', 'INSTITUTIONAL', 'ADOPTION', 'BULL', 'INFLOW'],
  top_news_headline:         'BlackRock BTC ETF records seventh consecutive day of net inflows amid institutional rotation',
  sentiment_label:           'BULLISH',
  sentiment_score:           74,
  sodex_tvl_usd:             847_000_000,
  sodex_volume_24h:          312_000_000,
  sodex_liquidity_tier:      'HIGH',
  data_sources:              ['SoSoValue ETF API', 'SoSoValue News API', 'SoDEX Liquidity API'],
  powered_by:                'SoSoValue API + SoDEX',
}